#!/bin/sh

# a mimic of the unix pick program

pick() {
    if test $# -eq 0; then
        while read -r line; do
            printf '%s (y,n,q) ' "$line" > /dev/tty
            read c < /dev/tty
            case "$c" in
                y) echo "$line";;
                n) ;;
                q) return;;
            esac
        done
        return
    fi

    for arg in "$@"; do
        printf '%s (y,n,q) ' "$arg" > /dev/tty
        read c < /dev/tty
        case "$c" in
            y) echo "$arg";;
            n) ;;
            q) return;;
        esac
    done
}

pick "$@"
